apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCgj4+mZMa0z+pPyWCU8M7U87b4oSt8Owl0/THrl+Evd6r7PytUVbWmCsprDk/bKYk5jK8ZVop11V1HyyPXROUU8lX+CnH5dST44edr/2lUAd97UMbecJ6231Xz6fGwBXFjEKJ1n/9m15lWhCQ2xZZr1YBYJ+PT/ApdmTA6fUVAwyZ0kLpcMwAN4tRhFvBjQB5QCbHgKwPLG/1HVr7cYUVZGw7EEsev/gafsBWJnqf7RgepHQczt+85yaKRknOT0YtFJcL13aSgbJxKcBG8W+QLcD0mJ33RLEIuGeAWXH273yqs/sQ/6Ik75TW2LACUTKmekWyl0kApXhcEu4Uuvwmgfd6H9gbtRNnzVgm7rxdHsfWhdM6kYKV1KobudmIUBl+mg7Si4rGP2ueILmY9BJGR5GfEhgd5CaI9DTaAkZy0arqRQUreIbioMmS5/kbFQ9wNZNwpWP28RI8YfNZGAEoIRKrgZsaXcNiPcnvHRLEY+w3HjiiTiGbqsd97vZJ3mJx9A0aIMKC0o0e7CMzdKXDPY11HduyumJhKSscxwr4hp+Xj0IiOY1O2LbOpcWkHXWQt9PqRaTmcy2ieyxNnQ0xbQhka7Fhb2Wk8G+OSWNr/gmsFlYyr82moOK58fB5lPC/TuhUTQ4XDwFNegufx4IKyLQra6QOCg7Or71U+c3D4xDjkno/rJrtQZ+x8kT8ELUycqPhN7xc6tHnqnIRrRkVeGl2CEVeiM9dB91PTWL6wf++z8svoUBzJsIhh5tSusuIGAwvc6ckvljo3v6wXNQk1iVmoGbhCKD0LBY07XLMrQQzS5MmBQHfnbFxihFA5aJ9abiubfOubMbvzGXFAsu6tYMgajAU8Bed3gZUlUzNITy1z6KOqLwVo75TOr32OHWEjcbuVRjutBuJ3MoeJuYGu1g==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default

