apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/pgo
    repoURL: https://github.com/<your-github-user>/<your-repo-name>.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
      - ServerSideApply=true
